### ISSUE TITLE
FIX extension no longer works: Could not establish connection

### ISSUE THREAD

**Issue by allanlaal** [franleplant/youtube-watch-later-mass-delete#1]
did it need to use the polymer design to work?

the error I get is:

> Could not establish connection. The receiving end does not exist

**Comment by franleplant** [comment]
Should need polymer, I think the problem is the css selector we are using,
I hope I can take look later

**Comment by franleplant** [comment]
Just submitted a new fixed version, should be generally available in 24 hours.
